### ISSUE TITLE
The plug-in was broken since webpack >= 3.7.0

### ISSUE THREAD

**Issue by ajhsu** [jalkoby/sass-webpack-plugin#5]
I found that `sass-webpack-plugin` could be broken when running with `webpack >= 3.7.0`;

Webpack will throw following error message during the compilation:
```
Uncaught TypeError: Cannot read property 'variables' of undefined
 at Compilation.processDependenciesBlocksForChunks (node_modules/webpack/lib/Compilation.js:949:12)
 at Compilation.seal (node_modules/webpack/lib/Compilation.js:591:8)
 at node_modules/webpack/lib/Compiler.js:508:17
 at node_modules/tapable/lib/Tapable.js:289:11
 at node_modules/webpack/lib/Compilation.js:507:11
 at node_modules/webpack/lib/Compilation.js:477:14
 at _combinedTickCallback (internal/process/next_tick.js:67:7)
 at process._tickCallback (internal/process/next_tick.js:98:9)
```

The same error occurred on CI build of the repo:
https://travis-ci.org/jalkoby/sass-webpack-plugin/builds/289890585

Not sure what is going on, but I made it work again by downgrading my webpack version into `~3.6.0`.

**Comment by jalkoby** [comment]
Feel free to upgrade the plugin to "0.3.4"
